In [4]:
import pandas as pd

tabela = pd.read_excel(r"C:\Users\Mikael\Downloads\Lista nomes casais.xlsx")

display (tabela)

,Nome,Email,RG,null
0,Ana Clara Soares dos Santos,acsoares568@gmail.com,30.691.661-0,20
1,Clara Marques Baptista,claramarques965@gmail.com,30.724.882-3,18
2,Eduarda Ferreira Peres de Amorim,eduardaferreiraperes@gmail.com,26.388.624-4,16
3,Felipe Costa Travassos,travassos.felipe@gmail.com,25.607.393-4,31
4,Guilherme de Medeiros Leite,guilhermedemedeirosleite@gmail.com,29.037.834-8,20
5,Julia Barreto Favorita Sciammrella,jusciammarella@gmail.com,29.779.815-9,19
6,Kainan de Moura Chami,kainanchami@gmail.com,32.276.895-3,18
7,Luã Lima Ribeiro,lualimaparadoxo@gmail.com,20.844.645-0,31
8,Luciana Abib Schreiner,lschreiner.com@gmaol.com,29.062.229-9,24
9,Luise Cecilia Aumuller,luise.aumuller@gmail.com,30.986.806-5,15
10,Maryane Cypriano Corrêa,maryanecypriano@gmail.com,28.428.772-4,20
11,Mikael Schwind Franco de Mesquita,mikael.mesquita@gmail.com,29.569.794-0,27
12,Tainá Silva Rocha,tainasilvarocha2@gmail.com,26.939.681-8,24

In [5]:
tabela = tabela.drop("null", axis = 1)
tabela = tabela.drop("Email", axis = 1)
display (tabela)

                                  Nome            RG
0          Ana Clara Soares dos Santos  30.691.661-0
1               Clara Marques Baptista  30.724.882-3
2     Eduarda Ferreira Peres de Amorim  26.388.624-4
3               Felipe Costa Travassos  25.607.393-4
4          Guilherme de Medeiros Leite  29.037.834-8
5   Julia Barreto Favorita Sciammrella  29.779.815-9
6                Kainan de Moura Chami  32.276.895-3
7                     Luã Lima Ribeiro  20.844.645-0
8               Luciana Abib Schreiner  29.062.229-9
9               Luise Cecilia Aumuller  30.986.806-5
10             Maryane Cypriano Corrêa  28.428.772-4
11   Mikael Schwind Franco de Mesquita  29.569.794-0
12                   Tainá Silva Rocha  26.939.681-8

In [6]:
tabela.to_string(r"C:\Users\Mikael\Downloads\Listas casais.txt",justify="left")